name: build-x64-Windows
on:
  push:
  workflow_call:
jobs:
  build-x64-Windows:
    runs-on: windows-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Ninja
        run: choco install ninja

      - name: Build
        run: utils/scripts/build_win_package.ps1

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ikulab-motion-viewer-x64-windows
          path: |
            ./ikulab-motion-viewer_Installer.exe
